"use client";
import { SnackbarProvider } from "notistack";
import { PersistGate } from "redux-persist/integration/react";
import { persistStore } from "redux-persist";
import { store } from "@/redux/store";
import { Provider } from "react-redux";
import CssBaseline from "@mui/material/CssBaseline";
import defaultTheme from "@/themes/defaultTheme";
import { ThemeProvider } from "@mui/material/styles";
import { CacheProvider, EmotionCache } from "@emotion/react";
import AuthGuard from "../components/authGuard/index";
import { createTheme } from "@/themes";
import { Suspense } from "react";
import Loading from "./loading";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Pension System",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  let persistor = persistStore(store);
  const theme = createTheme();
  return (
    <html lang="en">
      <head>
        <title>Pension System</title>
      </head>
      <body>
        <Provider store={store}>
          <PersistGate loading={null} persistor={persistor}>
            <ThemeProvider theme={theme}>
              <CssBaseline />
              <SnackbarProvider>
                <Suspense fallback={<Loading />}>
                  <AuthGuard>{children}</AuthGuard>
                </Suspense>
              </SnackbarProvider>
            </ThemeProvider>
          </PersistGate>
        </Provider>
      </body>
    </html>
  );
}
