"use client";
import { SnackbarProvider } from "notistack";

export const metadata = {
  title: "Pension System",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <SnackbarProvider>
        <body>{children}</body>
      </SnackbarProvider>
    </html>
  );
}
